version: 0.2

phases:
  install:
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 7.0

  pre_build:
    commands:
      - echo Pre-build started on `date`
      - dotnet restore

  build:
    commands:
      - echo Build started on `date`
      - dotnet build -c Release

  post_build:
    commands:
      - echo Post-build started on `date`
      - dotnet publish -c Release --output $CODEBUILD_SRC_DIR/publish_output

artifacts:
  files:
    - '**/*'
  base-directory: $CODEBUILD_SRC_DIR/publish_output
  discard-paths: no