version: 0.2

phases:
  
  pre_build:
    commands:
      - echo Pre-build started on `date`
      - dotnet restore

  build:
    commands:
      - echo Build started on `date`
      - dotnet build -c Release

  post_build:
    commands:
      - echo Post-build started on `date`
      - dotnet publish -c Release --output $CODEBUILD_SRC_DIR/publish_output

artifacts:
  files:
    - '**/*'
  base-directory: $CODEBUILD_SRC_DIR/publish_output
  discard-paths: no