# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --configuration Release --output ./publish
    - name: Install AWS CLI
      run: |
        Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
        iex "& { $(irm https://aka.ms/install-artifacts-credprovider.ps1 -UseMsi).Content }"
        pip install --user awscli
        - name: Deploy to EC2
    - name: Deploy to EC2
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1
        aws ssm send-command --document-name "AWS-RunPowerShellScript" --targets "Key=tag:Name,Values=<nome-da-instancia-EC2>" --parameters commands=New-Item -ItemType Directory -Path C:\App;aws s3 sync s3://<seu-bucket-do-S3> C:\App --region <sua-região-da-AWS> --wait
